interface Color {
    value: string;
    label: string;
}

// Color names from: https://bitfume.com/tools/hue-names/ Senaries (x96)
const LABELS: string[] = [
    'Red',
    'Cherry',
    'Scarlet',
    'Grapefruit',
    'Vermillion',
    'Clementine',
    'Pumpkin',
    'Orange Pumpkin',
    'Orange',
    'Tangor',
    'Tangerine',
    'Goldenrod',
    'Amber',
    'Gold',
    'Lemon',
    'Cantaloupe',
    'Yellow',
    'Lemon Lime',
    'Pear',
    'Honeydew',
    'Lime',
    'Spring Lime',
    'Spring Green',
    'Flora',
    'Chartreuse',
    'Chartreuse Lawn',
    'Lawn Green',
    'Harlequin Lawn',
    'Harlequin',
    'Harlequin Apple',
    'Green Apple',
    'Greener Apple',
    'Green',
    'Green Malachite',
    'Malachite',
    'Irish Malachite',
    'Erin',
    'Irish Luck',
    'Irish Emerald',
    'Irish Emerald Green',
    'Emerald',
    'Sea Spring',
    'Sea Foam',
    'Aquamarine Sea Foam',
    'Aquamarine',
    'Aquamarine Aqua',
    'Aqua',
    'Aqua Cyan',
    'Cyan',
    'Cyan Turquoise',
    'Turquoise',
    'Sky',
    'Capri',
    'Celestial Capri',
    'Celeste',
    'Celestial Azure',
    'Azure',
    'Azure Denim',
    'Denim',
    'Cerulean Denim',
    'Cerulean',
    'Persian Cerulean',
    'Persian Blue',
    'Bluer Persian Blue',
    'Blue',
    'Bluer Blue',
    'Blueberry',
    'Ocean',
    'Ultramarine',
    'Ultramarine Orchid',
    'Orchid',
    'Violet Orchid',
    'Violet',
    'Plum',
    'Electric Purple',
    'Energetic Purple',
    'Purple',
    'Far Out Purple',
    'Psychedelic Purple',
    'Carnation',
    'Magenta',
    'Warm Magenta',
    'Hot Magenta',
    'Hot Magenta Cerise',
    'Cerise',
    'Beverly Hills Cerise',
    'Hollywood Cerise',
    'Hollywood Rose',
    'Rose',
    'Strawberry Rose',
    'Strawberry',
    'Pomegranate',
    'Crimson',
    'Crimson Torch',
    'Torch Red',
    'Redder Torch Red',
];

export const hexValues = [
    '#ff0000',
    '#ff1000',
    '#ff2000',
    '#ff3000',
    '#ff4000',
    '#ff5000',
    '#ff6000',
    '#ff7000',
    '#ff8000',
    '#ff8f00',
    '#ff9f00',
    '#ffaf00',
    '#ffbf00',
    '#ffcf00',
    '#ffdf00',
    '#ffef00',
    '#ffff00',
    '#efff00',
    '#dfff00',
    '#cfff00',
    '#bfff00',
    '#afff00',
    '#9fff00',
    '#8fff00',
    '#80ff00',
    '#70ff00',
    '#60ff00',
    '#50ff00',
    '#40ff00',
    '#30ff00',
    '#20ff00',
    '#10ff00',
    '#00ff00',
    '#00ff10',
    '#00ff20',
    '#00ff30',
    '#00ff40',
    '#00ff50',
    '#00ff60',
    '#00ff70',
    '#00ff80',
    '#00ff8f',
    '#00ff9f',
    '#00ffaf',
    '#00ffbf',
    '#00ffcf',
    '#00ffdf',
    '#00ffef',
    '#00ffff',
    '#00efff',
    '#00dfff',
    '#00cfff',
    '#00bfff',
    '#00afff',
    '#009fff',
    '#008fff',
    '#0080ff',
    '#0070ff',
    '#0060ff',
    '#0050ff',
    '#0040ff',
    '#0030ff',
    '#0020ff',
    '#0010ff',
    '#0000ff',
    '#1000ff',
    '#2000ff',
    '#3000ff',
    '#4000ff',
    '#5000ff',
    '#6000ff',
    '#7000ff',
    '#8000ff',
    '#8f00ff',
    '#9f00ff',
    '#af00ff',
    '#bf00ff',
    '#cf00ff',
    '#df00ff',
    '#ef00ff',
    '#ff00ff',
    '#ff00ef',
    '#ff00df',
    '#ff00cf',
    '#ff00bf',
    '#ff00af',
    '#ff009f',
    '#ff008f',
    '#ff0080',
    '#ff0070',
    '#ff0060',
    '#ff0050',
    '#ff0040',
    '#ff0030',
    '#ff0020',
    '#ff0010',
];

const HUES: number[] = Array.from(
    { length: LABELS.length },
    (_, i) => +(i * 3.75).toFixed(2),
);

// Maps hue value to Color
export const COLOR_MAP = new Map<number, Color>(
    HUES.map((h, i) => [h, { label: LABELS[i], value: hexValues[i] }]),
);

// Maps hex value to hue value
export const HUE_MAP = new Map<string, number>(
    HUES.map((h, i) => [hexValues[i], h]),
);
